name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
       submodules: true


    - name: List files
      run: ls -R

    - name: Build the Docker image
      run: docker build --no-cache --target build -t hotel-review-system-build -f Docker/backend/Dockerfile .
    
