name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'amazon-corretto'
        java-version: '17'

    - name: Build Docker image
      run: docker build --target build -t hotel-review-system-build -f Docker/backend/Dockerfile .

    - name: Run Docker container
      run: docker run -e DB_URL=${{ secrets.DB_URL }} -e MAILDEV_URL=${{ secrets.MAILDEV_URL }} -e ACTIVE_PROFILE=dev -e JAR_VERSION=1.0.0 -p 8088:8088 hotel-review-system-build

